globalThis.NSFT_DEFAULTS = {
    enableViewRecordObject: true,
    viewRecordObjectTheme: "github-dark",
    viewRecordObjectThemeOverridden: false,

    enableViewScriptedRecord: true,
    enableRecordTrail: true,

    enableCopyFieldAndSublistIds: true,
    copyIdsNoButton: true,
    enableOpenCustomRecordBtn: true,
    enableSetFieldValues: true,
    setFieldValuesNoIcon: true,
    enableFindFieldById: true,
    findFieldHighlightColor: 'green',
    findFieldHighlightPersist: false,
    enableFieldInlinePreview: true,
    fieldInlinePreviewDelay: 200,
    enableSuiteletTools: true,

    enableCodeFieldPrettier: true,
    codeFieldPrettierTheme: "github-dark",

    enableFormatCodeFields: true,
    formatCodeFieldsOnBlur: false,
    enableRelatedNativeLinks: true,

    enableSaveAndEditButton: true,
    enableEditAndSaveButton: true,
    enableDeleteRecordButton: true,
    saveAndEditButtonMode: 'menu',
    editAndSaveButtonMode: 'menu',
    deleteRecordButtonMode: 'menu',
    editAndSaveConfirmInPrd: false,
    deleteRecordRequireTypeConfirm: true,
    enableCancelOverride: true,
    enableRecordOptionsMenu: true,
    enableRefreshSublist: true,

    enableAutogenerateIds: true,
    autogenerateIdsPrefix: '',
    enableLoadRecordConsole: true,

    enableLogPrettier: true,
    logPrettierTheme: "github-dark",
    enableLiveMode: true,
    liveModeInterval: 3,
    liveModeAutoStart: false,
    enableFullLogsButton: true,
    fullLogsOpenInNewTab: true,
    enableLogViewer: true,
    enableEditorTheme: true,
    editorTheme: "github-dark",
    editorThemeAutoSwitch: false,
    editorFontFamily: 'JetBrains Mono',
    editorFontSize: 14,
    editorCustomBg: '#1e1e1e',
    editorCustomFg: '#d4d4d4',
    editorCustomKeyword: '#569cd6',
    editorCustomLiteral: '#569cd6',
    editorCustomNumber: '#b5cea8',
    editorCustomString: '#ce9178',
    editorCustomVariable: '#9cdcfe',
    editorCustomProperty: '#9cdcfe',
    editorCustomComment: '#6a9955',
    enableEditorOpenInNewTab: true,
    enableScriptAutoName: true,

    enableCommandPalette: true,
    commandPaletteCustomUrls: [],
    enablePagePerformance: true,
    enableShortcutsCheatsheet: true,
    enableShortcutHints: true,
    enableGoToRecord: true,
    gotoRecordOverrideNative: true,
    gotoRecordFuzzy: false,
    enableRecentRecords: true,
    recentRecordsCacheTtl: 60,
    enableSandboxNumberBadge: true,
    enableOpenInOtherEnv: true,
    openInOtherEnvSandboxes: '1,2',
    enableFieldAuditQuickView: true,
    enableEnvBadge: true,
    envBadgeColorPrd: '#dc2626',
    envBadgeColorSb: '#16a34a',
    envBadgeColorRp: '#2563eb',
    enableProductionBanner: true,
    productionBannerPosition: 'bottom',
    enableUpdateNotice: true,
    enableGroupedTabs: true,
    enableGroupedTabsAutomatic: true,
    groupedTabsAutoUseCompanyName: true,
    groupedTabsAutoCollapse: false,
    enableColorThemes: true,
    enableDarkMode: false,
    darkModeStyle: 'gray',
    enableTurboMode: false,
    colorThemeHue: 216,
    colorThemeSat: 23,
    colorThemeLig: 49,
    enableBetterPageTitles: true,
    enableFixedSublistColumn: true,
    enableFixedSublistHeaders: true,
    enableFixedTabs: true,
    enableSmallerDropdownOptions: true,
    dropdownPixelHeight: 0,
    enableSmallerNavigationOptions: true,
    navigationPixelHeight: 30,
    enableSmallerMainMenu: true,
    mainMenuFontSize: 13,
    enableSmallerSublistHeaders: true,
    enableSublistFilter: true,
    enableSublistLineIds: true,
    enableProfileButton: true,
    enableAutoRefresh: true,
    autoRefreshInterval: 5,
    autoRefreshAutoStart: false,

    enableSuiteQLRunner: true,
    enableAiAssistant: true,
    aiAssistantPage: true,
    aiAssistantSuiteql: true,
    suiteqlTheme: "eclipse",
    suiteqlThemeOverridden: false,
    suiteqlHistoryMax: 30,
    suiteqlMaxRecords: 5000,

    enableSearchFieldsFinder: true,
    enableSavedSearchSplit: true,

    enableExportSearch: true,
    exportSearchTheme: "atom-one-dark",

    enableCopyAccountId: true,

    enableFileCabinetUtils: true,
    enableFileCabinetDownload: true,

    enableAdvancedPdfAutocomplete: true,
    enableAdvancedPdfPreview: true,
    enableAdvancedPdfVersions: true,

    enableCsvResponseViewer: true,
    enableInSearchPreview: true,
    enableQuickSearchCreation: true,
    quickSearchCreationTimeoutMs: 12000,
    enableSearchFormulaAutocomplete: true,

    enableLoadNModule: true,
    enableLogoutBlocker: true,
    enableHideGuidedLearning: true,

    nsftSelectorDiagnostics: false,
    enableJsonFormatter: true,
    jsonFormatterTheme: 'auto',
    jsonFormatterMaxAutoExpandDepth: 2,
    jsonFormatterMaxChildrenPreview: 60,
    enableDiscreetMode: false,
    enablePortletRefresher: false,
    portletRefresherInterval: 600,
    enableRoleFinder: true,
    enableScriptUpload: true,
    enableGithubBackup: true,
    githubBackupBranch: 'main',
    githubBackupPrefix: 'suitescripts',

    enableWfColoredTransitions: true,
    wfColoredTransitionsPalette: 'vivid',
    wfColoredTransitionsLineStyle: 'solid',
    wfColoredTransitionsLineWidth: 2,
    enableWorkflowSearcher: false,

    enableTextareaMinHeightBeta: true,
    enableMultiselectCounterBeta: true,
    enableFloatingFieldGroupsBeta: true,
    enableSublistLineNumbersBeta: true,
    enableMaxlengthCounterBeta: true,
    enableMultiselectHierarchyBeta: true,
    enableSublistPagingBeta: true,
    sublistPagingPageSize: 1,
    enableDropdownSizeBeta: true,
    dropdownSizeBetaPx: 400,
    enableBundleFilterLabelsBeta: true,
    enableLoginSandboxIndicatorBeta: true,
    enableBundleFolderNamesBeta: true,
    enableFileCabinetCopyPathBeta: true,
    enableLoginCompanyBrandingBeta: true,
    enableErrorPagePolishBeta: true,
    enableLoggedoutRedirectBeta: true,
    enableFileCabinetDragDropBeta: true,
    enableFileCabinetEditFileBeta: true,
    enableFileCabinetRenameBeta: true,
    enableFileCabinetDeleteBeta: true,
    enableFileCabinetFolderLinkBeta: true,
    enableFileRecordPreviewBeta: true,
    fileRecordPreviewTheme: 'atom-one-light',
    enableSystemFolderSafetyBeta: true,
    enableNetSuiteVersionBadgeBeta: true
};

globalThis.NSFT_SYNC_PRIMARY_KEYS = ['colorThemeHue', 'colorThemeSat', 'colorThemeLig'];

globalThis.NSFT_SYNC_MIRRORED_KEYS = [
    'enableEnvBadge',
    'envBadgeColorPrd',
    'envBadgeColorSb',
    'envBadgeColorRp',
    'quickSearchCreationLinks'
];
