globalThis.NSFT_DEFAULTS = {
    enableViewRecordObject: true,
    viewRecordObjectTheme: "atom-one-light",
    viewRecordObjectThemeOverridden: false,
    viewRecordObjectOpenMode: "modal",

    enableViewScriptedRecord: true,
    enableRecordLogsViewer: true,
    recordLogsViewerOpenMode: "modal",
    enableRecordTrail: true,

    enableCopyFieldAndSublistIds: true,
    enableSearchSummaryBulk: true,
    enableSearchFiltersBatch: true,
    copyIdsMode: 'shift',
    copyIdsNoButton: true,
    enableOpenCustomRecordBtn: true,
    enableSetFieldValues: true,
    setFieldValuesNoIcon: true,
    setFieldValuesShowHelp: true,
    setFieldValuesShowId: true,
    setFieldValuesShowValue: true,
    setFieldValuesShowText: true,
    setFieldValuesShowType: true,
    setFieldValuesShowFlags: true,
    setFieldValuesShowSetter: true,
    setFieldValuesShowOptions: true,
    setFieldValuesShowEdit: true,
    enableFindFieldById: true,
    findFieldHighlightColor: 'green',
    findFieldHighlightPersist: false,
    enableFieldInlinePreview: true,
    fieldInlinePreviewDelay: 200,
    enableSuiteletTools: true,

    enableCodeFieldPrettier: true,
    codeFieldPrettierTheme: "auto",

    enableFormatCodeFields: true,
    formatCodeFieldsOnBlur: false,
    enableRelatedNativeLinks: true,

    enableSaveAndEditButton: true,
    enableEditAndSaveButton: true,
    enableDeleteRecordButton: true,
    saveAndEditButtonMode: 'menu',
    editAndSaveButtonMode: 'menu',
    deleteRecordButtonMode: 'menu',
    editAndSaveConfirmInPrd: false,
    deleteRecordRequireTypeConfirm: true,
    enableCancelOverride: true,
    enableRecordOptionsMenu: true,
    recordOptionsMenuShowOpenCustom: true,
    recordOptionsMenuShowAddField: true,
    recordOptionsMenuShowAddColumn: true,
    recordOptionsMenuShowDependents: true,
    recordOptionsMenuShowCopyUrl: true,
    recordOptionsMenuShowOpenInEnv: true,
    recordOptionsMenuShowXml: true,
    enableRefreshSublist: true,

    enableAutogenerateIds: true,
    autogenerateIdsPrefix: '',
    enableLoadRecordConsole: true,

    enableLogPrettier: true,
    logPrettierTheme: "auto",
    enableLiveMode: true,
    liveModeInterval: 3,
    liveModeAutoStart: false,
    enableFullLogsButton: true,
    fullLogsOpenInNewTab: true,
    enableLogViewer: true,
    enableEditorTheme: true,
    enableEditorCloseAfterSave: true,
    editorTheme: 'auto',
    editorFontFamily: 'JetBrains Mono',
    editorFontSize: 14,
    editorCustomBg: '#1e1e1e',
    editorCustomFg: '#d4d4d4',
    editorCustomKeyword: '#569cd6',
    editorCustomLiteral: '#569cd6',
    editorCustomNumber: '#b5cea8',
    editorCustomString: '#ce9178',
    editorCustomVariable: '#9cdcfe',
    editorCustomProperty: '#9cdcfe',
    editorCustomComment: '#6a9955',
    enableEditorOpenInNewTab: true,
    enableAdvancedEditor: true,
    advancedEditorEngine: 'cm5',
    advancedEditorWrap: false,
    advancedEditorTree: true,
    advancedEditorMinimap: false,
    advancedEditorTheme: 'atom-one-light',
    advancedEditorThemeOverridden: false,
    advancedEditorRuler: 0,
    enableScriptAutoName: true,

    enableCommandPalette: true,
    enableCustomizationFinder: true,
    enableSuiteScriptConsole: true,
    suitescriptConsoleTheme: "atom-one-light",
    suitescriptConsoleThemeOverridden: false,
    suitescriptConsoleHistoryMax: 30,
    codeEditorKeymap: 'vscode',
    codeEditorInlayHints: true,
    codeEditorLightLines: 800,
    suitescriptConsoleAiComplete: true,
    suitescriptConsoleAiModel: "",
    commandPaletteCustomUrls: [],
    enablePagePerformance: true,
    enableShortcutsCheatsheet: true,
    enableShortcutHints: true,
    shortcutKeyStyle: "auto",
    enableGoToRecord: true,
    gotoRecordOverrideNative: true,
    gotoRecordFuzzy: false,
    enableRecentRecords: true,
    recentRecordsCacheTtl: 60,
    enableSandboxNumberBadge: true,
    enableOpenInOtherEnv: true,
    openInOtherEnvSandboxes: '1,2',
    enableFieldAuditQuickView: true,
    enableEnvBadge: true,
    envBadgeColorPrd: '#dc2626',
    envBadgeColorSb: '#16a34a',
    envBadgeColorRp: '#2563eb',
    envBadgeLetters: '3',
    enableProductionBanner: false,
    productionBannerPosition: 'bottom',
    enableUpdateNotice: true,
    enableGroupedTabs: true,
    enableGroupedTabsAutomatic: true,
    groupedTabsAutoUseCompanyName: true,
    groupedTabsAutoCollapse: false,
    enableColorThemes: false,
    enableDarkMode: false,
    darkModeStyle: 'gray',
    darkModeScope: 'all',
    enableTurboMode: false,
    colorThemeHue: 216,
    colorThemeSat: 23,
    colorThemeLig: 49,
    colorThemeMode: 'global',
    colorThemeByEnv: false,
    colorThemeEnvPrd: '#9a606a',
    colorThemeEnvSb: '#609a73',
    colorThemeEnvRp: '#60779a',
    colorThemeAccounts: {},
    enableBetterPageTitles: true,
    enableFixedSublistColumn: true,
    enableFixedSublistHeaders: true,
    enableFixedTabs: true,
    enableSmallerDropdownOptions: true,
    dropdownPixelHeight: 0,
    enableSmallerNavigationOptions: true,
    navigationPixelHeight: 30,
    enableSmallerMainMenu: true,
    mainMenuFontSize: 13,
    enableSmallerSublistHeaders: true,
    enableSublistFilter: true,
    enableSublistLineIds: true,
    enableProfileButton: true,
    enableAutoRefresh: true,
    autoRefreshInterval: 5,
    autoRefreshAutoStart: false,

    enableSuiteQLRunner: true,
    enableAiAssistant: true,
    aiAssistantPage: true,
    aiAssistantSuiteql: true,
    aiAssistantConsole: true,
    aiAssistantAdv: true,
    suiteqlTheme: "atom-one-light",
    suiteqlThemeOverridden: false,
    suiteqlHistoryMax: 30,
    suiteqlMaxRecords: 5000,
    suiteqlFetchAllRows: true,
    suiteqlFetchMethod: 'auto',
    suiteqlRestConcurrency: 4,
    suiteqlRestFillColumns: false,
    suiteqlManyRowsAction: 'ask',
    suiteqlManyRowsThreshold: 20000,
    suiteqlAutoSchema: true,
    suiteqlAiComplete: true,
    suiteqlAiModel: "",

    enableSearchFieldsFinder: true,
    enableSavedSearchSplit: true,

    enableExportSearch: true,
    exportSearchTheme: "auto",

    enableCopyAccountId: true,

    enableFileCabinetUtils: true,
    enableFileCabinetDownload: true,

    enableAdvancedPdfAutocomplete: true,
    enableAdvancedPdfPreview: true,
    enableAdvancedPdfVersions: true,

    enableCsvResponseViewer: true,
    enableInSearchPreview: true,
    enableQuickSearchCreation: true,
    quickSearchCreationTimeoutMs: 12000,
    enableSearchFormulaAutocomplete: true,

    enableLoadNModule: true,
    enableLogoutBlocker: true,
    enableHideGuidedLearning: true,

    nsftSelectorDiagnostics: false,
    enableJsonFormatter: true,
    jsonFormatterTheme: 'auto',
    jsonFormatterMaxAutoExpandDepth: 2,
    jsonFormatterMaxChildrenPreview: 60,
    enableDiscreetMode: false,
    enablePortletRefresher: true,
    portletRefresherInterval: 600,
    portletRefresherAutoStart: false,
    enableRoleFinder: true,
    enableScriptUpload: true,
    enableGithubBackup: true,
    githubBackupBranch: 'main',
    githubBackupPrefix: 'suitescripts',

    enableWfColoredTransitions: true,
    wfColoredTransitionsPalette: 'vivid',
    wfColoredTransitionsLineStyle: 'solid',
    wfColoredTransitionsLineWidth: 2,
    enableWorkflowSearcher: false,

    enableTextareaMinHeightBeta: true,
    enableMultiselectCounterBeta: true,
    enableFloatingFieldGroupsBeta: true,
    enableSublistLineNumbersBeta: true,
    enableMaxlengthCounterBeta: true,
    enableDateFormatHint: true,
    enableShiftRangeSelect: true,
    enableMultiselectHierarchyBeta: true,
    enableSublistPagingBeta: true,
    sublistPagingPageSize: 1,
    enableDropdownSizeBeta: true,
    dropdownSizeBetaPx: 400,
    enableBundleFilterLabelsBeta: true,
    enableLoginSandboxIndicatorBeta: true,
    enableBundleFolderNamesBeta: true,
    enableFileCabinetCopyPathBeta: true,
    enableLoginCompanyBrandingBeta: true,
    enableErrorPagePolishBeta: true,
    enableLoggedoutRedirectBeta: true,
    enableFileCabinetDragDropBeta: true,
    enableFileCabinetEditFileBeta: true,
    enableFileCabinetRenameBeta: true,
    enableFileCabinetDeleteBeta: true,
    enableFileCabinetFolderLinkBeta: true,
    enableFileRecordPreviewBeta: true,
    fileRecordPreviewTheme: 'auto',
    enableSystemFolderSafetyBeta: true,
    enableNetSuiteVersionBadgeBeta: true
};

globalThis.NSFT_AI_FAST = {
    nombres: {
        claude: 'Claude', gemini: 'Gemini', openai: 'OpenAI', deepseek: 'DeepSeek',
        mistral: 'Mistral', kimi: 'Kimi', grok: 'Grok', openrouter: 'OpenRouter'
    },
    rapidos: {
        claude: 'haiku',
        gemini: 'flash',
        openai: 'nano|mini',
        deepseek: 'chat|flash|lite',
        mistral: 'codestral|small',
        grok: 'fast|mini',
        kimi: 'instruct'
    },
    generico: 'haiku|flash|nano|mini|lite|fast|small|codestral|turbo'
};

globalThis.NSFT_SYNC_PRIMARY_KEYS = ['colorThemeHue', 'colorThemeSat', 'colorThemeLig'];

globalThis.NSFT_SYNC_MIRRORED_KEYS = [
    'enableEnvBadge',
    'envBadgeColorPrd',
    'envBadgeColorSb',
    'envBadgeColorRp',
    'envBadgeLetters',
    'colorThemeMode',
    'colorThemeByEnv',
    'colorThemeEnvPrd',
    'colorThemeEnvSb',
    'colorThemeEnvRp',
    'colorThemeAccounts',
    'quickSearchCreationLinks'
];
